export default {
    MAINPAGEBUTTON: 'MAINPAGE_BUTTON',
    ALL_FOOD_BUTTON: 'ALL_FOOD_BUTTON',
    PRODUCE_PAGE_BUTTON: 'PRODUCE_PAGE_BUTTON',
    MEAT_PAGE_BUTTON: 'MEAT_PAGE_BUTTON',
    SEAFOOD_PAGE_BUTTON: 'SEAFOOD_PAGE_BUTTON',
    NON_PERSIHABLES_PAGE_BUTTON: 'NON_PERSIHABLES_PAGE_BUTTON',
    PREFERENCEBUTTON: 'PREFERENCE_BUTTON',

}